### ISSUE TITLE
New Version v0.4.1 has broken the Resource Scanner

### ISSUE THREAD

**Issue by lukasmakegames** [derkork/godot-resource-groups#17]
The resource scanner now requires file_system:EditorFileSystem

My project is scanning resource groups in runtime.

var editor_settings = EditorInterface.get_editor_settings()

EditorFileSystem is only accesible by the editor, not in runtime.

The previous version v0.4.0 worked fine, but I wanted to stay updated.

![image](https://github.com/user-attachments/assets/166a7913-50ff-45b4-b351-a2e9814ba944)

**Comment by derkork** [comment]
The resource group scanner is not part of the public API (everything that is public has a `class_name`) as such it can change or even disappear in every version.

If you need a list of all resource groups in your project you could just make another resource group for that. E.g. if all your resource groups follow a naming convention (e.g. `xyz_group.tres`) you can make a resource group with

- Folder:  `data` 
- Includes: `**_group.tres`

Then you can use this as a "bootstrapping" resource group to get all the others in your project. Would that work for you?

**Comment by lukasmakegames** [comment]
I think that wouldn't work, I need rebuild resource groups in runtime as I change the base_folder in runtime. 

I have 'userproject' files loaded from godot game at 'userpath' out of godot project path and that 'userpath' changes with every 'userproject'

![image](https://github.com/user-attachments/assets/00b7a922-b0db-429b-a456-4dbabef5658f)

![image](https://github.com/user-attachments/assets/c65519b0-944d-42ee-b601-4caf258f09f5)

**Comment by derkork** [comment]
I don't have the full picture on the inner workings of your application, however if you need the old implementation for your game, I would suggest you download [0.4.0 ](https://github.com/derkork/godot-resource-groups/archive/refs/tags/v0.4.0.zip) and move the relevant files into your own code base (outside of the `addons` folder). Then you can also give them proper class names and make them part of your own implementation. This way you have full control over the process. 

I cannot reasonably go back to the old implementation because that was pretty slow and caused problems with projects using a lot of files. Given that this is also internal API, I think copying out the part you need for your game is the best course of action here.

**Comment by derkork** [comment]
Okay great, thanks for reporting back.
